version: '3.8'

services:
  question-microservice-db:
    container_name: question-microservice-db
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_questions_db:/var/lib/postgresql/data

  my-pgadmin:
    container_name: my-pgadmin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: myemail@example.com
      PGADMIN_DEFAULT_PASSWORD: mypassword
